document.addEventListener("DOMContentLoaded", async () => {
  await BCVData.load("../");
  if(BCVData.controls.global.boosterRequestsEnabled === false){
    insertFeatureBanner("main.page", "booster requests", "Booster pack and booster box requests are currently turned off by Bow.");
  }
  const U = BCVUtils;
  const box = document.getElementById("boosterGrid");
  const search = document.getElementById("search");
  const typeFilter = document.getElementById("typeFilter");

  function render() {
    let products = [...BCVData.boosters];
    const q = search.value.toLowerCase();
    if (q) products = products.filter(p => JSON.stringify(p).toLowerCase().includes(q));
    if (typeFilter.value) products = products.filter(p => p.type === typeFilter.value);

    box.innerHTML = products.map(p => {
      const isPack = p.type === "booster-pack";
      const imagePath = "../" + p.image;
      const isUnavailable = p.outOfStock || String(p.available).toLowerCase() === "false";
      const stockBadge = isUnavailable ? `<span class="badge out">Out of Stock</span>` : `<span class="badge auth">Available</span>`;
      const bc = BCVData.controls.boosters?.[p.id] || {};
      const productValue = BCVUtils.money(boosterEstimatedValue(p) || "");
      const productPrice = BCVUtils.money(boosterSalePrice(p));
      return `<article class="card ${p.outOfStock ? "out-card" : ""}">
        <img class="card-img" src="${U.escape(imagePath)}" onerror="this.src='../assets/placeholders/booster-placeholder.svg'">
        <div class="card-body">
          <div class="meta"><span class="badge warn">${isPack ? "Booster Pack" : "Booster Box"}</span>${stockBadge}${p.autoGenerated ? `<span class="badge">Auto Generated</span>` : ""}</div>
          <h3>${U.escape(p.name)}</h3>
          <p>${U.escape(p.description || "")}</p>
          <p class="value-line"><b>Estimated Value:</b> ${U.escape(productValue || "Not listed")}</p><p class="price-line"><b>Sale Price:</b> ${U.escape(productPrice || "Contact for pricing")}</p>
          <div class="card-actions">
            ${isUnavailable || BCVData.controls.global.boosterRequestsEnabled === false
              ? `<button class="disabled-action" disabled>${BCVData.controls.global.boosterRequestsEnabled === false ? "Requests Off" : "Out of Stock"}</button><a class="view-btn" href="booster.html?id=${encodeURIComponent(p.id)}">View Details</a><button class="secondary" onclick="shareItem('${U.escape(p.name)}','Check out this Bow Card Vault booster product','booster.html?id=${encodeURIComponent(p.id)}')">Share</button>`
              : isPack 
                ? `<button class="cart-btn" onclick="addRandomPack('${U.escape(p.id)}')">Add to Cart</button><a class="view-btn" href="booster-builder.html?set=${encodeURIComponent(p.setName)}">Customize</a><a class="view-btn" href="booster.html?id=${encodeURIComponent(p.id)}">View Details</a><button class="secondary" onclick="shareItem('${U.escape(p.name)}','Check out this Bow Card Vault booster pack','booster.html?id=${encodeURIComponent(p.id)}')">Share</button>`
                : `<button class="cart-btn" onclick="addBoosterBox('${U.escape(p.id)}')">Add to Cart</button><a class="view-btn" href="booster.html?id=${encodeURIComponent(p.id)}">View Details</a><button class="secondary" onclick="shareItem('${U.escape(p.name)}','Check out this Bow Card Vault booster box','booster.html?id=${encodeURIComponent(p.id)}')">Share</button>`
            }
          </div>
        </div>
      </article>`;
    }).join("") || "<section class='empty'>No booster products found.</section>";
  }

  search.oninput = render;
  typeFilter.onchange = render;
  render();
});

function addRandomPack(id) { BCVCart.add(id, "random-booster-pack"); }
function addBoosterBox(id) { BCVCart.add(id, "booster-box"); }
