document.addEventListener("DOMContentLoaded", async () => {
  await BCVData.load("../");
  const U = BCVUtils;
  const id = new URLSearchParams(location.search).get("id");
  const p = boosterById(id);
  const wrap = document.getElementById("boosterPage");

  if(!p){
    wrap.innerHTML = "<section class='empty'>Booster product not found.</section>";
    return;
  }

  const bc = BCVData.controls.boosters?.[p.id] || {};
  const status = boosterStatus(p);
  const isPack = p.type === "booster-pack";
  const img = "../" + p.image;
  const value = BCVUtils.money(boosterEstimatedValue(p) || "Not listed");
  const sale = BCVUtils.money(boosterSalePrice(p) || "Contact for pricing");
  const details = bc.details || p.details || p.description || "Booster details are manually updated by Bow.";
  const sharePath = "booster.html?id=" + encodeURIComponent(p.id);

  wrap.innerHTML = `<section class="detail">
    <div class="gallery">
      <img class="main-img" src="${U.escape(img)}" onerror="this.src='../assets/placeholders/booster-placeholder.svg'">
    </div>
    <div>
      <p class="eyebrow">${isPack ? "Booster Pack" : "Booster Box"}</p>
      <h1>${U.escape(p.name)}</h1>
      <div class="meta">
        <span class="badge warn">${U.escape(p.type)}</span>
        <span class="badge ${status === "Available" ? "ok" : "no"}">${status}</span>
        ${p.autoGenerated ? `<span class="badge">Auto Generated</span>` : ""}
      </div>
      <div class="kv">
        <b>Set</b><span>${U.escape(p.setName || "")}</span>
        <b>Estimated Value</b><span>${U.escape(value)}</span>
        <b>Sale Price</b><span>${U.escape(sale)}</span>
        <b>Status</b><span>${U.escape(status)}</span>
      </div>
      <h2>Details</h2>
      <p>${U.escape(details)}</p>
      <div class="actions">
        ${status !== "Available" || BCVData.controls.global.boosterRequestsEnabled === false
          ? `<button class="disabled-action" disabled>${BCVData.controls.global.boosterRequestsEnabled === false ? "Requests Off" : "Out of Stock"}</button>`
          : isPack
            ? `<button class="cart-btn" onclick="addRandomPack('${U.escape(p.id)}')">Add Random Pack</button><a class="view-btn" href="booster-builder.html?set=${encodeURIComponent(p.setName)}">Customize Pack</a>`
            : `<button class="cart-btn" onclick="addBoosterBox('${U.escape(p.id)}')">Add to Cart</button>`
        }
        <button class="secondary" onclick="shareItem('${U.escape(p.name)}','Check out this Bow Card Vault booster product','${sharePath}')">Share</button>
        <a class="secondary" target="_blank" href="${facebookShareUrl(sharePath)}">Share on Facebook</a>
      </div>
    </div>
  </section>`;
});
function addRandomPack(id) { BCVCart.add(id, "random-booster-pack"); }
function addBoosterBox(id) { BCVCart.add(id, "booster-box"); }
